//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReliableWcfService.Demo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDemoService")]
    public interface IDemoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetSampleData", ReplyAction="http://tempuri.org/IDemoService/GetSampleDataResponse")]
        string GetSampleData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/GetSampleData", ReplyAction="http://tempuri.org/IDemoService/GetSampleDataResponse")]
        System.Threading.Tasks.Task<string> GetSampleDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/PerformSampleOperation", ReplyAction="http://tempuri.org/IDemoService/PerformSampleOperationResponse")]
        void PerformSampleOperation(string parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoService/PerformSampleOperation", ReplyAction="http://tempuri.org/IDemoService/PerformSampleOperationResponse")]
        System.Threading.Tasks.Task PerformSampleOperationAsync(string parameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoServiceChannel : ReliableWcfService.Demo.ServiceReference1.IDemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoServiceClient : System.ServiceModel.ClientBase<ReliableWcfService.Demo.ServiceReference1.IDemoService>, ReliableWcfService.Demo.ServiceReference1.IDemoService {
        
        public DemoServiceClient() {
        }
        
        public DemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSampleData() {
            return base.Channel.GetSampleData();
        }
        
        public System.Threading.Tasks.Task<string> GetSampleDataAsync() {
            return base.Channel.GetSampleDataAsync();
        }
        
        public void PerformSampleOperation(string parameter) {
            base.Channel.PerformSampleOperation(parameter);
        }
        
        public System.Threading.Tasks.Task PerformSampleOperationAsync(string parameter) {
            return base.Channel.PerformSampleOperationAsync(parameter);
        }
    }
}
